TARGET = output

TARGET: main.c person.c person.h ../include/string_functions/string_functions.c ../include/string_functions/string_functions.h
	gcc main.c person.c ../include/string_functions/string_functions.c -o output